name: Solar System Workflow - Matrix Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb://127.0.0.1:27017/solar-system'
  NODE_ENV: test

jobs:
  unit-testing:
    name: Node.js ${{ matrix.node }} Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18, 20]  # 👈 You can test across Node.js versions

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies (including dev)
        run: npm install --include=dev

      - name: Seed MongoDB
        run: node seed.js

      - name: Run Unit Tests
        run: npm test

      - name: Archive Test Results
        uses: actions/upload-artifact@main
        with:
          name: Mocha-Test-Result-Node${{ matrix.node }}
          path: test-results.xml
